# Generated by Django 4.2.3 on 2024-01-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbookingmodel',
            name='screentype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theatershowmodel',
            name='screentype',
            field=models.CharField(max_length=50),
        ),
    ]
