# Generated by Django 4.2.3 on 2024-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_seatbookingmodel_screentype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('occupation', models.JSONField(default=list)),
                ('born', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(max_length=100)),
                ('spouse', models.CharField(max_length=50)),
            ],
        ),
    ]
