# Generated by Django 4.2.3 on 2024-01-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fullname',
        ),
        migrations.AddField(
            model_name='person',
            name='cast_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.castmodel'),
        ),
        migrations.AddField(
            model_name='person',
            name='crew_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.crewmodel'),
        ),
    ]
