# Generated by Django 4.2.3 on 2024-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_person_fullname_person_cast_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
