# Generated by Django 4.2.3 on 2024-01-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_person_birthplace_alter_person_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
