# Generated by Django 4.2.3 on 2024-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_person_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='about',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='occupation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='spouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='about',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='occupation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='spouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
