# Generated by Django 4.2.3 on 2024-01-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_castmodel_about_castmodel_birthplace_castmodel_born_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='movie_role',
        ),
        migrations.RemoveField(
            model_name='crewmodel',
            name='role',
        ),
    ]
