# Generated by Django 4.2.3 on 2024-01-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_castmodel_about_alter_crewmodel_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmodel',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='crewmodel',
            name='movie',
        ),
        migrations.AddField(
            model_name='castmodel',
            name='movies_cast',
            field=models.ManyToManyField(related_name='cast_members', to='api.moviemodel'),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='movies_crew',
            field=models.ManyToManyField(related_name='crew_members', to='api.moviemodel'),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies_cast_members', to='api.castmodel'),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='movies_crew_members', to='api.crewmodel'),
        ),
    ]
